name: build pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: external workflow
    uses: tehw0lf/workflows/.github/workflows/build-test-publish.yml@main
    permissions:
      actions: write
      contents: write
      packages: write
    with:
      event_name: ${{ github.event_name }}
      install: "apt-get install curl && curl -LsSf https://astral.sh/uv/install.sh | sh"
      test: test_system.sh
      tool: bash
    secrets: inherit
